# Mod Properties

version = 3.0.0

# Your mod id should be descriptive, ideally just your mod's name in all lowercase with no hyphens or underscores.
mod_id = playerupgrades

mod_name = Player Upgrades

# Your group should be a unique identifier in reverse domain format.
group = ca.modmonster

description=A mod that adds upgrades to enhance your player!

# Fill out these URLs with links to your website or project page, sources (if public), issue tracker and Discord invite.
homepage = https://modrinth.com/mod/player-upgrades
sources = https://github.com/modmonster/PlayerUpgrades3
issues = https://github.com/modmonster/PlayerUpgrades3/issues
discord = https://discord.gg/zbheHAS

# Make sure the license here matches the one you defined in the LICENSE file.
license=MIT

mod_author = ModMonster

# Credits can include other attribution as well, such as artists, etc.
credits =

# Publishing Properties
# You can find the project ID on the CurseForge / Modrinth project page. You can leave this empty until you publish your mod.
curseforge_project_id = 0
curseforge_environments = Client,Server
modrinth_project_id = tj2WSFYJ

# If you have a Maven to deploy to, configure its URLs here.
# maven_releases = https://
# maven_snapshots = https://

# Build Properties
# The Java version to use. Different Minecraft versions require different Java versions.
java_version = 25

# The loaders to include.
include_fabric=true
include_neoforge=true
include_forge=true

# You can develop against published NeoForge snapshots (instead of releases) by adding the URL linked in the NeoForge PR here and updating the NeoForge version in gradle/libs.versions.toml.
neoforge_snapshot_url =

# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
